FROM  balenalib/raspberrypi4-64-python:3.9.10 As base

#FROM  python:3.7 As base
RUN pip install notebook

RUN echo "install tensorflow"
RUN pip install tensorflow-aarch64 -f https://tf.kmtea.eu/whl/stable.html
RUN echo "install done"

FROM base AS serial

RUN echo "installing pandas, numpy, matplotlib, plotly, RPi.GPIO, pyserial , and python"

RUN pip install pandas numpy matplotlib plotly RPi.GPIO pyserial

COPY . .

RUN echo "Running testseiral.ipynb"

#CMD ["./nbook_tsnb_run.sh"]
CMD ["./nbook_tf_run.sh"]