FROM python:3.7 As base

#FROM  balenalib/raspberrypi400-64-ubuntu-python:3.9 As base
# FROM  python:3.7 As base
# RUN echo "upgrade pip"
# RUN pip install --upgrade pip
# RUN echo "upgrade done"

RUN echo "installing notebook"
RUN python -m pip install psutil#RUN pip install notebook
RUN echo "install done"

RUN echo "install tensorflow"
RUN pip install tensorflow-aarch64 -f https://tf.kmtea.eu/whl/stable.html
RUN echo "install done"

FROM base AS serial

RUN echo "installing pandas, numpy, matplotlib, plotly, RPi.GPIO, pyserial , and python"

#RUN pip install pandas numpy matplotlib plotly
RUN pip install pandas numpy matplotlib plotly RPi.GPIO pyserial
COPY . .

RUN echo "Running testseiral.ipynb"

#CMD ["jupyter",  "--version"]
CMD ["python",  "--version"]
#CMD ["./nbook_tsnb_run.sh"]
#CMD ["./nbook_tf_run.sh"]