FROM  python:3.9.2 As base

RUN pip install notebook

FROM base AS serial

RUN echo "installing pandas, numpy, matplotlib, plotly, RPi.GPIO, pyserial , and python"

RUN pip install pandas numpy matplotlib plotly RPi.GPIO pyserial

COPY . .

RUN echo "Running testseiral.ipynb"

CMD ["./nbook_tsnb_run.sh"]